$(document).ready(function() {
    $('#p1').click(function(){
        window.location.href="portfolio/p1(linkedin).html";
    });
    $('#p2').click(function(){
        window.location.href="portfolio/p2(summit).html";
    });
    $('#p3').click(function(){
        window.location.href="portfolio/p3(pnp).html";
    });
    $('#p4').click(function(){
        window.location.href="portfolio/p4(zspace).html";
    });
    $('#p5').click(function(){
        window.location.href="portfolio/p5(microsoft).html";
    });
    $('#p6').click(function(){
        window.location.href="portfolio/p6(hcii).html";
    });
    $('#p7').click(function(){
        window.location.href="portfolio/p7(design).html";
    });
    $('#p8').click(function(){
        window.location.href="portfolio/p8(college).html";
    });
    $('#p9').click(function(){
        window.location.href="portfolio/p9(high_school).html";
    });
});